### ISSUE TITLE
Connection issues to database after long running period

### ISSUE THREAD

**Issue by lusu007** [kryoniteorg/kryo-discord-whitelist#13]
**Describe the bug**
After a long-running period of the server, the plugin cant get or update any SQL data. Therefore its not possible to join the server.

**To Reproduce**
1. Let the server running for an extended period.
2. Try to join the server.

**Expected behavior**
Even after a long period I should be able to join the server.

**Additional context**
```
[11:12:39 ERROR] [org.kryonite.kryodiscordwhitelist.velocity.listener.PlayerListener]: Failed to get or update player
java.sql.SQLNonTransientConnectionException: (conn=9583) Connection reset by peer
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[?:?]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158) ~[?:?]
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163) ~[?:?]
        at org.kryonite.kryodiscordwhitelist.common.persistence.repository.impl.MariaDbUserRepository.get(MariaDbUserRepository.java:101) ~[?:?]
        at org.kryonite.kryodiscordwhitelist.velocity.listener.PlayerListener.onPlayerLogin(PlayerListener.java:24) ~[?:?]
        at org.kryonite.kryodiscordwhitelist.velocity.listener.Lmbda$10.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Connection reset by peer
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:323) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
        ... 11 more
Caused by: java.sql.SQLNonTransientConnectionException: Connection reset by peer
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:2090) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:323) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
        ... 11 more
Caused by: java.net.SocketException: Connection reset by peer
        at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
        at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
        at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
        at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
        at org.mariadb.jdbc.internal.io.output.StandardPacketOutputStream.flushBuffer(StandardPacketOutputStream.java:111) ~[?:?]
        at org.mariadb.jdbc.internal.io.output.AbstractPacketOutputStream.flush(AbstractPacketOutputStream.java:186) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:316) ~[?:?]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
        ... 11 more
```

**Comment by lusu007** [comment]
As it looks, Hikari alone did not fix the error. 

```
[21:47:05 ERROR] [org.kryonite.kryodiscordwhitelist.velocity.listener.PlayerListener]: Failed to get or update player
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
        at org.kryonite.kryodiscordwhitelist.common.persistence.repository.impl.MariaDbUserRepository.get(MariaDbUserRepository.java:101) ~[?:?]
        at org.kryonite.kryodiscordwhitelist.velocity.listener.PlayerListener.onPlayerLogin(PlayerListener.java:24) ~[?:?]
        at org.kryonite.kryodiscordwhitelist.velocity.listener.Lmbda$10.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
